# Generated by Django 5.2.2 on 2025-06-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_pickuppoint_remove_order_route_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
        migrations.AddField(
            model_name='order',
            name='departure_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='dbms.pickuppoint', verbose_name='Пункт отправления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='dbms.pickuppoint', verbose_name='Пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес пункта'),
        ),
    ]
