# Generated by Django 5.2.2 on 2025-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_alter_pickuppoint_options_order_departure_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
