# Generated by Django 5.2.2 on 2025-06-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0004_order_amount_order_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
