# Generated by Django 5.2.2 on 2025-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
